### ISSUE TITLE
Error: [data-js="blog-article-list"] does not exist

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#1720]
https://sentry.is.staging.canonical.com/canonical/snapcraftio/issues/1263/

```
Error: [data-js="blog-article-list"] does not exist
  at new e (./static/js/public/snap-details/blog-posts.js:21:13)
  at Module.E (./static/js/public/snap-details/blog-posts.js:75:21)
  at f.<anonymous> (/publisher/jetbrains:599:26)
  at f.d (/static/js/modules/raven.min.js:2:4672)
  at f.context (/static/js/modules/raven.min.js:2:4476)
...
(1 additional frame(s) were not displayed)
```

**Comment by bartaz** [comment]
And I never noticed it locally because it's wrapped in try/catch and never shows up in the console as error...
