### ISSUE TITLE
TypeError: Cannot read property 'innerHTML' of null

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#917]
https://sentry.io/canonical-bm/snapcraftio/issues/618290890/

```
TypeError: Cannot read property 'innerHTML' of null
  at new ChannelMap (../public/snap-details/channelMap.js:9:29)
  at Object.channelMap (../public/snap-details/channelMap.js:427:10)
  at f.<anonymous> (/bitwarden:595:28)
  at f.d (/static/js/modules/raven.min.js:2:4672)
  at f.context (/static/js/modules/raven.min.js:2:4476)
...
(1 additional frame(s) were not displayed)
```

**Comment by bartaz** [comment]
Still happening quite a lot.

**Comment by bartaz** [comment]
My guess is that maybe the `[data-js=...]` selector doesn't work reliably, so maybe switching to something basic like `getElementById` would help? 

Or making sure that the script runs after DOM is fully loaded?

**Comment by Lukewh** [comment]
Hopefully fixed by https://github.com/canonical-websites/snapcraft.io/pull/952
